GetOrgTeamsData/index.js
GithubRepoScanOrchestrator/helper.js
GithubRepoScanOrchestrator/index.js
HttpStartOrgScan/index.js
SaveLdifToStorage/index.js
integration-api-default-config-mi.json
integration-api-default-config.json

crux :
The key of external id is not changed, just the value. 
test workspace - https://test-app-flow-2.leanix.net/IntHubTest/factsheet/Microservice/049345ff-50fb-48b4-9bfa-738e63870de4
---
test MI v1 workspace - https://test-app-flow-2.leanix.net/GithubMIVersion/factsheet/Team/9b6e0c5c-1cba-4a73-9c39-77c0e6a024c3/history
To Test the migration:
1. A test Integration API is set up [here](https://test-app-flow-2.leanix.net/GithubMIVersion/admin/integration-api/test2/test2/1.0.0/inbound/full)
2. Change this [factsheet](https://test-app-flow-2.leanix.net/GithubMIVersion/factsheet/Microservice/f5dff2a1-a8e8-4a77-93c6-2dbcb8b01875) github ID to `MDEwOlJlcG9zaXRvcnk1OTExMDEwOA==`
3. Run the above Integration API 
4. After Integration API completes the factsheet github external id should be …

Feature/cid 382/change to readable externalid

---

GetAllRepositoriesForOrg/index.js
GetOrgTeamsData/index.js
GithubRepoScanOrchestrator/index.js
README.md

Attached generated LDIFs in case of `repoNamesExcludeList` is passed with `business-*` even the `customer-success` team also do not include `leanix/business-transformation-mgmt`
[Archive.zip](https://github.com/leanix/github-repository-connector/files/7580387/Archive.zip)

Feature/cid 352/ignore non org repos

---

ihub-resources/connector-definition-australiaeast.json
ihub-resources/connector-definition-canadacentral.json
ihub-resources/connector-definition-eastus.json
ihub-resources/connector-definition-germanywestcentral.json
ihub-resources/connector-definition-test.json
ihub-resources/connector-definition-westeurope.json

https://leanix.atlassian.net/wiki/spaces/FLOW/pages/7464358115/Integration+Hub+-+Getting+started+creating+a+Connector#Registering-a-system-wide-connector-(INTERNAL-ONLY-AS-SYSTEM-OR-SUPERADMIN-REQUIRED)

Feature/cid 416/add docs link ihub

---

GetOrgTeamsData/index.js
GithubRepoScanOrchestrator/index.js
Lib/connectorLogger.js

@talha-shafqat
@aravindmetku updated connectorLogger.ts console error msg here as well.

Feature/cid 308/remove func names logs

---

GithubRepoScanOrchestrator/index.js

As discussed in today's review. making teams data part of the LDIF. Everything else should be working as it is.
---
test - https://demo-eu.leanix.net/ARMMicroserviceIntelligence/admin/integration-api/github-connector/github-connector/1.0.0/inbound/full

CID-433 teams data is part of the LDIF even if importTeams flags is set to false. But the iapi processor will not trigger.

---

integration-api-default-config.json

Test WS : https://test-app-flow-2.leanix.net/VSMWS2WSPCI/inventory/new

CID-479: removeall tags for github tracking

---

integration-api-default-config.json

Changes due to leanix/provisioning-service#347

CID-397 rename data source tag name

---

integration-api-default-config.json

https://test-app-flow-2.leanix.net/MuleSoftIntegrationTest/factsheet/Microservice/23555fcd-5627-46b0-a341-531a46055f64

CID-452: retain category on SWA FS

---

GithubRepoScanOrchestrator/index.js

due to the conversation here - https://leanix.slack.com/archives/C01J2RW5WFR/p1642580240049500

CID-515 increase the scanner capacity to 500. This should not hit the rate limit.

---

GetSubReposData/index.js
GithubRepoScanOrchestrator/index.js

iteration #1 to handle secondary rate limit which seems to be the actual case of the customer.
--
test - https://test-app-flow-2.leanix.net/IntHubTest/admin/integration-hub/ca577ed9-b2d8-44c9-b71b-3b5e18f885d8

Feature/cid 515/handle large repos

---

GetAllRepositoriesForOrg/index.js
GetOrgTeamsData/index.js
GetReposVisibilityData/index.js
GetSubReposData/index.js
GithubRepoScanOrchestrator/index.js
Lib/GitHubClient.js

- retry mechanism
- improved logging
Test:
https://test-app-flow-2.leanix.net/IntHubTest/admin/integration-hub/ca577ed9-b2d8-44c9-b71b-3b5e18f885d8

Feature/cid 515/add ihub status update

---

GithubRepoScanOrchestrator/index.js
Lib/GitHubClient.js
Lib/connectorLogger.js
package-lock.json
package.json

todo: add the rate limit check for all function executions
test- https://test-app-flow-2.leanix.net/IntHubTest/admin/integration-hub/ca577ed9-b2d8-44c9-b71b-3b5e18f885d8

CID-515 control teams concurrency. add sleep with ihub update process.

---

integration-api-default-config-mi.json
integration-api-default-config.json

Updated the processors to delete `Github repository` tag on `"Team", "Microservice", "TechnicalComponent"` factsheet type

CID-494: Delete un-used tag - `Github repository`

---

GithubRepoScanOrchestrator/index.js
Lib/GitHubClient.js

Using input binding the same way as others.
As discussed in azure documentation, to maintain the determinism using the input binding the same way we are using for other activity function calls.
---
test - https://test-app-flow-2.leanix.net/IntHubTest/admin/integration-hub/ca577ed9-b2d8-44c9-b71b-3b5e18f885d8

CID-515 fix non determinism error for test connector activity function call in orchestration

---

GithubRepoScanOrchestrator/index.js
Lib/GitHubClient.js

test - https://test-app-flow-2.leanix.net/IntHubTest/admin/integration-hub/ca577ed9-b2d8-44c9-b71b-3b5e18f885d8

CID-515 update ihub if the last query in activity function is >5 minutes

---

GithubRepoScanOrchestrator/index.js

Test connector check will be followed
--
test - https://test-app-flow-2.leanix.net/IntHubTest/admin/integration-hub/ca577ed9-b2d8-44c9-b71b-3b5e18f885d8

CID-515 do not fetch team if flag is false

---

GetOrgTeamsData/index.js
GithubRepoScanOrchestrator/index.js
Lib/helper.js

Feature/cid 515/data limit check

---

package-lock.json
package.json

Upgrade durable-functions dependency version

CID-538 Improper Privilege Management in shelljs

---

Lib/helper.js

In the screenshot, since I could not bring 400000 records, I just used a lesser limit, but the overall structure would be the same.

CID-515: add exceeded records to the error msg

---

GithubRepoScanOrchestrator/index.js
Lib/helper.js

Refactored orchestrator functions to class to reduce dependency of sending `context, logger` in function parameters

Refactor/cid 496/orchestrator functions to class

---

GetSubReposData/index.js
GithubRepoScanOrchestrator/index.js
Lib/helper.js
README.md
SaveLdifToStorage/index.js
TestConnector/index.js
ihub-resources/connector-definition.json
integration-api-default-config.json

test - https://test-app-flow-2.leanix.net/IntHubTest/admin/integration-hub/e5a49426-f98a-4ea1-816c-c2bff0708d7c

Feature/cid 496/detect monorepo

---

integration-api-default-config.json

CID-496 setting 'Yes' for monorepo attr

---

Lib/helper.js
integration-api-default-config.json

https://user-images.githubusercontent.com/71264988/163985759-6b0e371d-7350-4e7e-b031-d6eb1dfa5693.mov

CID-658: Generate unique(team/<org>/<team name>) GitHub ID for Team FactSheets

---

Lib/HttpClient.js
Lib/helper.js

As discussed yesterday, adding a 100ms timeout after event register
BEFORE adding 100ms time, time taken to register events for leanix-internal with certain exclusion list is : 
Start Time: 2022-04-20T06:44:24.690Z
End Time:  2022-04-20T06:55:22.012Z
Time Taken: 11 min (approx)
AFTER adding 100ms time, time taken to register events for leanix-internal with certain exclusion list is : 
Start Time: 2022-04-20T06:20:51.803Z
End Time:  2022-04-20T06:35:01.990Z
Time Taken: 15min (approx)

CID-587: add wait after post cal httpClient

---

GithubRepoScanOrchestrator/index.js
Lib/HttpClient.js
SendMonoRepoEventsForDORA/function.json
SendMonoRepoEventsForDORA/index.js
integration-api-default-config.json

Add DORA metrics to mono-repos
Update isArchived flag to handle missing field when processing

CID-671 Add DORA metrics to mono-repos

---

integration-api-default-config.json

Working with the test ldif - https://test-app-flow-2.leanix.net/IntHubTest/admin/integration-api/CID-673-tag-sm/CID-673-tag-sm/1.0.0/inbound/full
check the swa fs - https://test-app-flow-2.leanix.net/IntHubTest/factsheet/Microservice/ddd380f6-c07d-4aeb-8510-a5de9eac41b5

CID-673 fix tag creation filter to check the archived swa to add tags to avoid warnings

---

ihub-resources/connector-definition.json

updated docs to point to old readmeio page

updated docs to point to old readme docs
